# Generated by Django 2.2.6 on 2020-12-03 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20201203_2133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Revenue',
        ),
    ]
